# Generated by Django 3.2.3 on 2021-05-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='images',
            field=models.ImageField(default='SOME STRING', upload_to='images/'),
        ),
    ]
